### ISSUE TITLE
Feature request: posibility to set raw and jpg folders location separately

### ISSUE THREAD

**Issue by ghost** [FoxP/dRAW#1]
If possible, please add a possibility to set jpg files location separately from raws (in some cases jpgs aren't stored in the same folder with raws). 
Thanks for this very useful utility!

**Comment by FoxP** [comment]
Yup, definitely on my TODO list. My new camera has same behavior : raw files are not stored in same folder.
I will try to do a quick update before the end of the year.

> Thanks for this very useful utility!

You're welcome. :)

**Comment by FoxP** [comment]
@andrewgmusic : I just published a new version.
Let me know if it's better now. ;)

![image](https://user-images.githubusercontent.com/16615901/199000687-3c3609c9-f110-4186-becf-8f16f953a8e1.png)

**Comment by ghost** [comment]
Works like a charm, thank you!
